# === DATABASE ===
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shop_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === JWT ===
# Генерация примера: openssl rand -base64 32
# Ключ должен быть Base64-строкой длиной >= 256 бит (32 байта)
jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleS0xMjM0NTY3ODk=}

# === HTTPS ===
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:server.jks
server.ssl.key-store-type=JKS
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:serverPass}
server.ssl.key-alias=server
