# === ТЕСТОВЫЙ ПРОФИЛЬ ===
# SSL отключён — keystore.p12 не нужен при запуске тестов
server.ssl.enabled=false
server.port=8080

# JWT тестовый ключ (Base64 от строки длиной 32 байта)
jwt.secret=dGVzdC1zZWNyZXQta2V5LWZvci10ZXN0cy0xMjM0NQ==
